# Generated by Django 3.0.14 on 2022-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moviemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Releasedate', models.DateField()),
                ('Name', models.CharField(max_length=30)),
                ('Actor', models.CharField(max_length=20)),
                ('Actress', models.CharField(max_length=20)),
                ('Ratings', models.FloatField()),
            ],
        ),
    ]
